version: "3.6"

services:
    database_ignite:
        image: postgres
        container_name: queries_challenge
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=queries_challenge
        volumes:
            - pgdata:/data/postgres
volumes:
    pgdata:
        driver: local